// Generated by CoffeeScript 1.3.3
(function() {
  var _this = this;

  d3.json("assets/primariePdData.json", function(data) {
    var barWidth, d, height, vis, votes, width, x, y;
    votes = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        d = data[_i];
        _results.push(d["votes"]);
      }
      return _results;
    })();
    barWidth = 40;
    width = (barWidth + 10) * data.length;
    height = 200;
    x = d3.scale.linear().domain([0, data.length]).range([0, width]);
    y = d3.scale.linear().domain([d3.min(votes), d3.max(votes)]).range([0, height]);
    console.log(x(2));
    console.log(y(1444));
    vis = d3.select('#graph').append('svg:svg').attr('width', width).attr('height', height);
    return vis.selectAll('rect').data(data).enter().append("svg:rect").attr("x", function(datum, index) {
      return x(index);
    }).attr("y", function(datum) {
      return height - y(datum.votes);
    }).attr("width", barWidth).attr("height", function(datum) {
      return y(datum.votes);
    });
  });

}).call(this);
